name: Regionerator
main: com.github.jikoo.regionerator.Regionerator
version: 1.3.0
author: Jikoo
softdepend:
- Multiverse-Core
- Factions
- GriefPrevention
- Landlord
- Towny
- WorldGuard

commands:
 regionerator:
  aliases: [regeninfo]
  description: Check Regionerator's progress, stop/start, or reload configuration.
  permission: regionerator.command
  usage: /regionerator [pause|resume|reload] (no arguments for a report)
