name: Regionerator
main: com.github.jikoo.regionerator.Regionerator
version: ${project.version}
author: Jikoo
softdepend:
- ASkyBlock
- Factions
- Feudal
- GriefPrevention
- Kingdoms
- Landlord
- Multiverse-Core
- RedProtect
- Residence
- Towny
- WorldGuard

commands:
 regionerator:
  aliases: [regeninfo]
  description: Check Regionerator's progress, stop/start, or reload configuration.
  permission: regionerator.command
  usage: /regionerator [pause|resume|reload] (no arguments for a report)
